#!/usr/bin/env bash
sudo apt-get install libncurses5-dev libncursesw5-dev
sudo apt-get install make
sudo yum group install "Development Tools"
sudo yum install ncurses-devel
sudo dnf group install "Development Tools"
sudo dnf install ncurses-devel
mkdir obj
echo "attempting to install ncurses"
make
