#!/usr/bin/env bash
echo "installing ncurses"
sudo apt-get install libncurses5-dev libncursesw5-dev
sudo apt-get install make
sudo yum group install "Development Tools"
sudo yum install ncurses-devel
sudo dnf group install "Development Tools"
sudo dnf install ncurses-devel
mkdir obj
make
eval mkdir "~$USER"/.unblind/
eval mkdir "~$USER"/.unblind/"language-syntax"/
eval cp ../"language\ syntax"/* "~$USER"/.unblind/"language-syntax"/
echo "install complete!"
